import { type TransformerFn, type EmitFn } from './Transpiler';

import * as api from './api';
import * as lang from './lang';
import * as tr from './ts';

export * from './Transpiler';

export const TRANSFORMERS: TransformerFn[] = [
  tr.transformFunctionArity,
  tr.removeNonNullExpression,
  tr.removeNonNullAssertion,
  // must run before the async transforms — it resolves field types through
  // the checker, which requires nodes attached to the original source
  tr.transformFieldInitializersUsingThis,
  tr.transformAsyncFunction,
  tr.transformAsyncFunctionExpression,
  tr.transformAsyncMethod,
  tr.transformAsyncArrowFunction,
  tr.transformPromiseHandlerArity,
  tr.transformDestructuredVariableDeclarationInCatch,
  tr.transformDestructuredVariableDeclarationInForOf,
  tr.transformMethodOnObject,
  tr.transformDestructuredParameterDeclaration,
  tr.transformPowExpression,
  tr.transformLocalTypeNames,
  tr.transformTemplateLiteralType,
  tr.transformMappedType,
  tr.transformKeyofTypeOperator,
  tr.transformTemplateExpression,
  tr.transformDeleteExpression,
  tr.transformGenericArrowFunctionDeclaration,
  tr.addDefaultPublicModifier,
];

// Order here actually matters (to some extent)
export const EMITTERS: EmitFn[] = [
  api.transformJsApiAccess,
  api.transformJsIdentifiers,
  api.transformBindThis,
  api.transformPromiseCatch,
  api.transformHasOwnProperty,
  api.transformSymbolCall,
  api.transformDateConstruction,
  api.transformConstructorAccess,
  api.transformSliceWithoutArguments,
  api.transformRegexApi,
  api.transformTsLibTypes,
  api.transformExternalTypeReference,
  lang.transformMissingTypeArguments,
  lang.transformJsDoc,
  lang.transformImportDeclaration,
  lang.transformArrayDestructuringAssignment,
  lang.transformVariableStatement,
  lang.transformVariableDeclarationList,
  lang.transformVariableDeclaration,
  lang.transformObjectBindingPattern,
  lang.transformArrayBindingPattern,
  lang.transformBooleanOperatorAsValue,
  lang.transformClassDeclaration,
  lang.transformEnumDeclaration,
  lang.transformIndexedAccessType,
  lang.transformHeritageClause,
  lang.transformConstructor,
  lang.transformClassPropertyDeclaration,
  lang.transformClassMethodDeclaration,
  lang.transformClassGetter,
  lang.transformClassSetter,
  lang.transformForLoop,
  lang.transformForOfLoop,
  lang.transformForInLoop,
  lang.transformSwitchCase,
  lang.transformNotOperator,
  lang.transformInstanceOfExpression,
  lang.transformConditions,
  lang.transformObjectLiteralExpression,
  lang.transformEnumMemberType,
  lang.transformInterfaceCallSignatures,
  lang.transformStructuralInterface,
  lang.transformCallSignature,
  lang.transformPropertySignature,
  lang.transformIndexSignature,
  lang.transformMethodSignature,
  lang.transformConstructorSignature,
  lang.transformPropertyAssignment,
  lang.transformShorthandPropertyAssignment,
  lang.transformElementAccess,
  lang.transformElementWriteToObject,
  lang.transformIncrementDecrementOnObject,
  lang.transformGetSet,
  lang.transformConflictingStaticAccess,
  lang.transformUnionMemberAccess,
  lang.transformArrowFunction,
  lang.transformFunctionParameter,
  lang.transformNewExpression,
  lang.transformCallExpression,
  lang.transformVoidExpression,
  lang.transformAsExpression,
  lang.transformTypeofExpression,
  lang.transformTypeParameter,
  lang.transformIntersectionType,
  lang.transformTypePredicate,
  lang.transformConstructorType,
  lang.transformGenericFunctionType,
  lang.transformConditionalType,
  lang.transformTypeQuery,
  lang.transformRegex,
  lang.transformSimpleTemplate,
  lang.transformTemplateExpression,
  lang.transformTemplateParts,
  lang.transformLiteralTypes,
  lang.transformArrayType,
  lang.transformUnionType,
  lang.transformTupleType,
  lang.transformKeywords,
  lang.transformRenameSymbol,
  lang.transformIdentifier,
];
